name: Flutter Auto Build APK

on:
  push:
    branches:
      - main # Memicu build setiap kali push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Tarik Kode dari Repository
        uses: actions/checkout@v4

      - name: Setup Java Jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Menggunakan versi stabil yang kebal dari error Groovy
          channel: 'stable'

      - name: Ambil Dependensi Project
        run: flutter pub get

      - name: Jalankan Perangkat Pembuat Gambar/Splash
        run: |
          flutter pub run flutter_launcher_icons
          flutter pub run flutter_native_splash:create

      - name: Compile Menjadi APK Debug/Release
        run: flutter build apk --debug

      - name: Upload File APK Hasil Jadi
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Hapkido-APK
          path: build/app/outputs/flutter-apk/app-debug.apk