- name: Compile Menjadi APK Debug
        run: |
          flutter clean
          flutter pub get
          cd android
          # JURUS BARU: Beri izin eksekusi agar ./gradlew bisa jalan
          chmod +x gradlew
          ./gradlew clean
          cd ..
          flutter build apk --debug --android-skip-build-dependency-validation